name: test-hello

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: test hello
    - uses: actions/checkout@v2
    - run: make say-hello
